//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.DAL.BookServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/BMS.WcfService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookServiceReference.IBookService")]
    public interface IBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Addbook", ReplyAction="http://tempuri.org/IBookService/AddbookResponse")]
        bool Addbook(BMS.DAL.BookServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Addbook", ReplyAction="http://tempuri.org/IBookService/AddbookResponse")]
        System.Threading.Tasks.Task<bool> AddbookAsync(BMS.DAL.BookServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Updatebook", ReplyAction="http://tempuri.org/IBookService/UpdatebookResponse")]
        bool Updatebook(BMS.DAL.BookServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Updatebook", ReplyAction="http://tempuri.org/IBookService/UpdatebookResponse")]
        System.Threading.Tasks.Task<bool> UpdatebookAsync(BMS.DAL.BookServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Deletebook", ReplyAction="http://tempuri.org/IBookService/DeletebookResponse")]
        bool Deletebook(int BookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Deletebook", ReplyAction="http://tempuri.org/IBookService/DeletebookResponse")]
        System.Threading.Tasks.Task<bool> DeletebookAsync(int BookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SearchBook", ReplyAction="http://tempuri.org/IBookService/SearchBookResponse")]
        BMS.DAL.BookServiceReference.Book SearchBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SearchBook", ReplyAction="http://tempuri.org/IBookService/SearchBookResponse")]
        System.Threading.Tasks.Task<BMS.DAL.BookServiceReference.Book> SearchBookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ShowBook", ReplyAction="http://tempuri.org/IBookService/ShowBookResponse")]
        BMS.DAL.BookServiceReference.Book[] ShowBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ShowBook", ReplyAction="http://tempuri.org/IBookService/ShowBookResponse")]
        System.Threading.Tasks.Task<BMS.DAL.BookServiceReference.Book[]> ShowBookAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceChannel : BMS.DAL.BookServiceReference.IBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<BMS.DAL.BookServiceReference.IBookService>, BMS.DAL.BookServiceReference.IBookService {
        
        public BookServiceClient() {
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Addbook(BMS.DAL.BookServiceReference.Book book) {
            return base.Channel.Addbook(book);
        }
        
        public System.Threading.Tasks.Task<bool> AddbookAsync(BMS.DAL.BookServiceReference.Book book) {
            return base.Channel.AddbookAsync(book);
        }
        
        public bool Updatebook(BMS.DAL.BookServiceReference.Book book) {
            return base.Channel.Updatebook(book);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatebookAsync(BMS.DAL.BookServiceReference.Book book) {
            return base.Channel.UpdatebookAsync(book);
        }
        
        public bool Deletebook(int BookID) {
            return base.Channel.Deletebook(BookID);
        }
        
        public System.Threading.Tasks.Task<bool> DeletebookAsync(int BookID) {
            return base.Channel.DeletebookAsync(BookID);
        }
        
        public BMS.DAL.BookServiceReference.Book SearchBook(int id) {
            return base.Channel.SearchBook(id);
        }
        
        public System.Threading.Tasks.Task<BMS.DAL.BookServiceReference.Book> SearchBookAsync(int id) {
            return base.Channel.SearchBookAsync(id);
        }
        
        public BMS.DAL.BookServiceReference.Book[] ShowBook() {
            return base.Channel.ShowBook();
        }
        
        public System.Threading.Tasks.Task<BMS.DAL.BookServiceReference.Book[]> ShowBookAsync() {
            return base.Channel.ShowBookAsync();
        }
    }
}
