//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlPractice_Emp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustID { get; set; }
        public string CustName { get; set; }
        public Nullable<int> Premium { get; set; }
        public Nullable<int> Installment { get; set; }
        public string Comments { get; set; }
    }
}
