//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWcfLayeredDemo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBookService")]
    public interface IBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/DeleteBook", ReplyAction="http://tempuri.org/IBookService/DeleteBookResponse")]
        bool DeleteBook(int BookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/DeleteBook", ReplyAction="http://tempuri.org/IBookService/DeleteBookResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookAsync(int BookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/UpdateBook", ReplyAction="http://tempuri.org/IBookService/UpdateBookResponse")]
        bool UpdateBook(BMS.DAL.BookServiceReference.Book bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/UpdateBook", ReplyAction="http://tempuri.org/IBookService/UpdateBookResponse")]
        System.Threading.Tasks.Task<bool> UpdateBookAsync(BMS.DAL.BookServiceReference.Book bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/AddBook", ReplyAction="http://tempuri.org/IBookService/AddBookResponse")]
        bool AddBook(BMS.DAL.BookServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/AddBook", ReplyAction="http://tempuri.org/IBookService/AddBookResponse")]
        System.Threading.Tasks.Task<bool> AddBookAsync(BMS.DAL.BookServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SearchBook", ReplyAction="http://tempuri.org/IBookService/SearchBookResponse")]
        BMS.DAL.BookServiceReference.Book SearchBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/SearchBook", ReplyAction="http://tempuri.org/IBookService/SearchBookResponse")]
        System.Threading.Tasks.Task<BMS.DAL.BookServiceReference.Book> SearchBookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ShowBook", ReplyAction="http://tempuri.org/IBookService/ShowBookResponse")]
        BMS.DAL.BookServiceReference.Book[] ShowBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ShowBook", ReplyAction="http://tempuri.org/IBookService/ShowBookResponse")]
        System.Threading.Tasks.Task<BMS.DAL.BookServiceReference.Book[]> ShowBookAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceChannel : AspWcfLayeredDemo.ServiceReference1.IBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<AspWcfLayeredDemo.ServiceReference1.IBookService>, AspWcfLayeredDemo.ServiceReference1.IBookService {
        
        public BookServiceClient() {
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DeleteBook(int BookID) {
            return base.Channel.DeleteBook(BookID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookAsync(int BookID) {
            return base.Channel.DeleteBookAsync(BookID);
        }
        
        public bool UpdateBook(BMS.DAL.BookServiceReference.Book bookID) {
            return base.Channel.UpdateBook(bookID);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBookAsync(BMS.DAL.BookServiceReference.Book bookID) {
            return base.Channel.UpdateBookAsync(bookID);
        }
        
        public bool AddBook(BMS.DAL.BookServiceReference.Book book) {
            return base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task<bool> AddBookAsync(BMS.DAL.BookServiceReference.Book book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public BMS.DAL.BookServiceReference.Book SearchBook(int id) {
            return base.Channel.SearchBook(id);
        }
        
        public System.Threading.Tasks.Task<BMS.DAL.BookServiceReference.Book> SearchBookAsync(int id) {
            return base.Channel.SearchBookAsync(id);
        }
        
        public BMS.DAL.BookServiceReference.Book[] ShowBook() {
            return base.Channel.ShowBook();
        }
        
        public System.Threading.Tasks.Task<BMS.DAL.BookServiceReference.Book[]> ShowBookAsync() {
            return base.Channel.ShowBookAsync();
        }
    }
}
